fxs_users:
  - name: 'fxstreaming'
    uid: 1001
    groups: adm
    ssh_key: files/ssh_keys/users/id_rsa.pub

fxs_pip_base_packages:
  - virtualenv
  - virtualenvwrapper

fxs_apt_base_packages:
  - 'python-setuptools'
  - git
