- name: install base software
  apt:
    name: "{{ item }}"
  with_items: fxs_apt_base_packages

- name: install pip
  easy_install: name=pip

- name: install pip base packages
  pip:
    name: "{{ item }}"
  with_items: fxs_pip_base_packages

- name: create users
  user:
    name: "{{ item.name }}"
    uid: "{{ item.uid }}"
    append: yes
    groups: "{{ item.groups }}"
    shell: /bin/bash
  with_items: fxs_users

- name: put authorized keys
  authorized_key:
    key: "{{ lookup('file', item.ssh_key) }}"
    user: "{{ item.name }}"
    exclusive: yes
  with_items: fxs_users

- name: copy deploy key
  copy:
    src: files/ssh_keys/code_deploy/id_rsa.secure
    dest: "/home/{{ fxs_user }}/.ssh/id_rsa"
    owner: "{{ fxs_user }}"
    group: "{{ fxs_user }}"
    mode: 0400

- name: create project dir
  file:
    path: "/home/{{ fxs_user }}/{{ fxs_user }}"
    state: directory
    owner: "{{ fxs_user }}"
    group: "{{ fxs_user }}"
    mode: 0755
